In [1]:
#importing packages
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
from sklearn.impute import SimpleImputer

In [3]:
#data preprocessinng
dataset = pd.read_csv(r"C:\Users\MOHITH\OneDrive\Desktop\STUDY MATERIALS\ML\Machine Learning A-Z (Codes and Datasets)\Part 1 - Data Preprocessing\Data.csv")
X=dataset.iloc[:, :-1].values
Y=dataset.iloc[:, -1].values

#imputer is used to take care of missing data
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(X[:,1:3])
X[:,1:3]=imputer.transform(X[:,1:3])

# print(X)
print(dataset)

   Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes


In [4]:
#one hot encoder is used to give binary numbers to the feature names.
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer

ct= ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[0])],remainder='passthrough')
X=np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [5]:
#label encoder is used to give binary code to yes or no.
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y=le.fit_transform(Y)
print(y)

[0 1 0 0 1 1 0 1 0 1]


In [6]:
#splitting the data
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2)

In [7]:
print(X_train)

[[0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 48.0 79000.0]]


In [8]:
print(X_test)

[[0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [9]:
#scaling the data or feature scaling
from sklearn.preprocessing import StandardScaler
sc= StandardScaler()
X_train[:,3:]= sc.fit_transform(X_train[:,3:])
X_test[:,3:]= sc.transform(X_test[:,3:])

In [10]:
print(X_train)

[[0.0 1.0 0.0 -0.07601794972038149 -0.14599251694623933]
 [1.0 0.0 0.0 -0.8809138879361869 -0.6834516943766451]
 [0.0 1.0 0.0 1.5337739267112294 1.6420928233510708]
 [0.0 0.0 1.0 -0.39797632500670366 -0.4043863522493192]
 [0.0 0.0 1.0 -0.2727702901731338 -1.241582378631297]
 [1.0 0.0 0.0 0.5678988008522629 0.6188532355508758]
 [0.0 1.0 0.0 -1.6858098261519923 -1.0555388172130795]
 [1.0 0.0 0.0 1.2118155514249072 1.2700057005146361]]
